import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";

export default defineConfig({
    plugins: [
        laravel({
            input: [
							// "resources/sass/app.scss",
							// "resources/js/app.js"
							// "resources/assets/images/brand/favicon.ico" ,
							// "resources/assets/plugins/bootstrap/css/bootstrap.css",
							// "resources/assets/css-rtl/style.css" ,
							// "resources/assets/css-rtl/dark.css" ,
							// "resources/assets/css-rtl/skin-modes.css" ,
							// "resources/assets/css-rtl/animated.css" ,
							// "resources/assets/css-rtl/sidemenu.css" ,
							// "resources/assets/plugins/p-scrollbar/p-scrollbar.css" ,
							// "resources/assets/css-rtl/icons.css" ,
							// "resources/assets/plugins/sidebar/sidebar.css" ,
							// "resources/assets/plugins/select2/select2.min.css" ,
							// "resources/assets/plugins/jvectormap/jqvmap.css" ,
							// "resources/assets/plugins/datatable/css/dataTables.bootstrap4.min-rtl.css" ,
							// "resources/assets/plugins/time-picker/jquery.timepicker.css" ,
							// "resources/assets/plugins/jQuery-countdowntimer/jQuery.countdownTimer.css" ,
							// "resources/assets/css-rtl/style-rtl.css" ,
							// "resources/dist/select2.min.css",
							// "resources/assets/ersianDateTimePicker-bs4/src/jquery.md.bootstrap.datetimepicker.style.css",
							// "resources/assets/plugins/jquery/jquery.min.js" ,
							// "resources/assets/plugins/moment/moment.js" ,
							// "resources/assets/plugins/bootstrap/popper.min.js" ,
							// "resources/assets/plugins/bootstrap/js/bootstrap.min.js" ,
							// "resources/assets/plugins/othercharts/jquery.sparkline.min.js" ,
							// "resources/assets/plugins/sidemenu/sidemenu.js" ,
							// "resources/assets/plugins/p-scrollbar/p-scrollbar.js" ,
							// "resources/assets/plugins/p-scrollbar/p-scroll1.js" ,
							// "resources/assets/plugins/sidebar/sidebar.js" ,
							// "resources/assets/plugins/select2/select2.full.min.js" ,
							// "resources/assets/plugins/peitychart/jquery.peity.min.js" ,
							// "resources/assets/plugins/peitychart/peitychart.init.js" ,
							// "resources/assets/plugins/apexchart/apexcharts.js" ,
							// "resources/assets/plugins/vertical-scroll/jquery.bootstrap.newsbox.js" ,
							// "resources/assets/plugins/vertical-scroll/vertical-scroll.js" ,
							// "resources/assets/plugins/date-picker/jquery-ui.js" ,
							// "resources/assets/plugins/chart/chart.bundle.js" ,
							// "resources/assets/plugins/chart/utils.js" ,
							// "resources/assets/plugins/time-picker/jquery.timepicker.js" ,
							// "resources/assets/plugins/time-picker/toggles.min.js" ,
							// "resources/assets/plugins/chart.min/chart.min.js" ,
							// "resources/assets/plugins/chart.min/rounded-barchart.js" ,
							// "resources/assets/plugins/jQuery-countdowntimer/jQuery.countdownTimer.js" ,
							// "resources/assets/js/index1.js" ,
							// "resources/assets/js/custom.js" ,
							// "resources/dist/select2.min.js" ,
							// "resources/assets/PersianDateTimePicker-bs4/src/jquery.md.bootstrap.datetimepicker.js",
						],
            refresh: true,
        }),
    ],
});
